export const mockTechnicians = [
  {
    id: 1,
    name: 'John Doe',
    services: ['Computer Repair'],
    email: 'john_doe@example.com',
    latitude: -34.867542,
    longitude: -56.225611,
    specialization: 'Computer Repair',
    phone: '123-456-7890',
    location: 'New York, NY',
  },
  {
    id: 2,
    name: 'Jane Smith',
    services: ['Phone Repair'],
    email: 'jane_smith@example.com',
    latitude: -34.819867,
    longitude: -56.077208,
    specialization: 'Phone Repair',
    phone: '123-456-7890',
    location: 'Los Angeles, CA',
  },
  {
    id: 3,
    name: 'Alice Jones',
    services: ['TV Repair'],
    email: 'alice_jones@example.com',
    latitude: -34.903727,
    longitude: -54.907409,
    specialization: 'TV Repair',
    phone: '123-456-7890',
    location: 'Chicago, IL',
  },
];